/*
 * Copyright 2004 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.ancientprogramming.fixedformat4j.issues;

import com.ancientprogramming.fixedformat4j.annotation.Align;
import com.ancientprogramming.fixedformat4j.annotation.Field;
import com.ancientprogramming.fixedformat4j.annotation.FixedFormatBoolean;
import com.ancientprogramming.fixedformat4j.annotation.FixedFormatDecimal;
import com.ancientprogramming.fixedformat4j.annotation.FixedFormatNumber;
import com.ancientprogramming.fixedformat4j.annotation.FixedFormatPattern;
import com.ancientprogramming.fixedformat4j.annotation.Record;
import com.ancientprogramming.fixedformat4j.annotation.Sign;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;

/**
 * A Lombok-powered record used to verify field-level annotation support.
 * Getters and setters are generated by Lombok; all mapping annotations are placed on fields.
 *
 * Layout (1-based offsets):
 *   1-10  : name (String, left-aligned, space-padded)
 *   11-15 : age (Integer, right-aligned, zero-padded)
 *   16-23 : birthDate (Date, pattern yyyyMMdd)
 *   24    : active (Boolean, Y/N)
 *   25-34 : salary (BigDecimal, 2 implicit decimals, right-aligned, zero-padded)
 */
@Getter
@Setter
@NoArgsConstructor
@Record
public class LombokRecord {

  @Field(offset = 1, length = 10)
  private String name;

  @Field(offset = 11, length = 5, align = Align.RIGHT, paddingChar = '0')
  private Integer age;

  @Field(offset = 16, length = 8)
  @FixedFormatPattern("yyyyMMdd")
  private Date birthDate;

  @Field(offset = 24, length = 1)
  @FixedFormatBoolean(trueValue = "Y", falseValue = "N")
  private Boolean active;

  @Field(offset = 25, length = 10, align = Align.RIGHT, paddingChar = '0')
  @FixedFormatDecimal(decimals = 2, useDecimalDelimiter = false)
  @FixedFormatNumber(sign = Sign.NOSIGN)
  private BigDecimal salary;
}
